apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-frontend
    tier: frontend
  name: httpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: httpd-frontend
        tier: frontend
    spec:
      containers:
        - image: httpd
          name: httpd
