apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-backend
    tier: backend
  name: httpd-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-backend
      tier: backend
  template:
    metadata:
      labels:
        app: httpd-backend
        tier: backend
    spec:
      containers:
        - image: httpd
          name: httpd
