apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kedapoc-scaledobject
  namespace: kedapoc
  annotations:
    # autoscaling.keda.sh/paused: "true" # Optional. Use to pause autoscaling of objects explicitly
spec:
  scaleTargetRef:
    name: httpd-frontend
  pollingInterval: 1 # Optional. Default: 30 seconds
  cooldownPeriod: 30 # Optional. Default: 300 seconds
  minReplicaCount: 1 # Optional. Default: 0
  maxReplicaCount: 25 # Optional. Default: 100

  triggers:
    - type: postgresql
      metadata:
        userName: app
        passwordFromEnv: PG_PASSWORD
        host: kedapoc-database-rw.kedapoc.svc.cluster.local
        port: "5432"
        dbName: app
        sslmode: disable
        query: "SELECT count(*) FROM queue.messages WHERE status = 'new';"
        targetQueryValue: "1"
